
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 09 11:21:58 CST 2016
//----------------------------------------------------

package tarea4;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int rrequest = 2;
  public static final int raiz = 31;
  public static final int igual2 = 52;
  public static final int creartienda = 16;
  public static final int eliminar = 23;
  public static final int corchc = 44;
  public static final int sucursal = 38;
  public static final int corcha = 43;
  public static final int crearusuario = 8;
  public static final int correo = 58;
  public static final int img = 19;
  public static final int tienda = 14;
  public static final int coma = 21;
  public static final int igual = 20;
  public static final int identificador = 60;
  public static final int direccion = 13;
  public static final int productos = 55;
  public static final int de = 46;
  public static final int guion = 7;
  public static final int llavec = 30;
  public static final int llavea = 29;
  public static final int ror = 50;
  public static final int puntoycoma = 41;
  public static final int telefono = 11;
  public static final int modificar = 39;
  public static final int marca = 35;
  public static final int email = 12;
  public static final int propietario = 18;
  public static final int EOF = 0;
  public static final int iniciousuario = 3;
  public static final int parc = 28;
  public static final int mas = 24;
  public static final int producto = 33;
  public static final int nombre = 9;
  public static final int para = 27;
  public static final int error = 1;
  public static final int color = 36;
  public static final int tiendas = 54;
  public static final int entero = 56;
  public static final int modificacion = 22;
  public static final int pot = 32;
  public static final int mate = 40;
  public static final int por = 25;
  public static final int rnot = 51;
  public static final int rand = 49;
  public static final int contrasena = 5;
  public static final int cons = 42;
  public static final int id = 4;
  public static final int rget = 53;
  public static final int tipo = 15;
  public static final int donde = 47;
  public static final int tamano = 37;
  public static final int cantidad = 34;
  public static final int apellido = 10;
  public static final int codigo = 17;
  public static final int dolar = 6;
  public static final int extraer = 45;
  public static final int div = 26;
  public static final int query = 48;
  public static final int decimal = 59;
  public static final int cadena = 57;
}

